services:
  postgres:
    image: postgres:16-alpine
    container_name: psico-app-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: psico_user
      POSTGRES_PASSWORD: psico_pass
      POSTGRES_DB: psico_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: